### ISSUE TITLE
Sending cache control headers for static resources

### ISSUE THREAD

**Issue by jaroel** [nksaraf/vinxi#140]
My static content (images, css, javascript) is fully cacheable, in client and in-between-proxies. Do we have a way to turn on automatic cache control headers, ie immutable/public?

This is using a Solid Start setup, though I'd guess that Vinxi would/should be handling this?

**Comment by nksaraf** [comment]
This is in production I am assuming. Yeah you can use the [Route rules](https://nitro.unjs.io/guide/routing#route-rules) feature from nitro. This allows you add runtime custom behaviour to any set of routes:


In vinxi, you would use it as such:

```ts
import { createApp } from "vinxi";

export default createApp({
	server: {
		routeRules: {
		  '/_build/assets/**': { headers: { 'cache-control': 's-maxage=0' } },
		  '/api/v1/**': { cors: true, headers: { 'access-control-allow-methods': 'GET' } },
		  '/old-page': { redirect: '/new-page' },
		  '/proxy/example': { proxy: 'https://example.com' },
		  '/proxy/**': { proxy: '/api/**' },
		}
	}
})
```
In solid-start's config you would configure it as such:

```ts
import { defineConfig } from "@solidjs/start/config"

export default defineConfig({
	start: {
		server: {
			routeRules: {
			  '/_build/assets/**': { headers: { 'cache-control': 's-maxage=0' } },
			  '/api/v1/**': { cors: true, headers: { 'access-control-allow-methods': 'GET' } },
			  '/old-page': { redirect: '/new-page' },
			  '/proxy/example': { proxy: 'https://example.com' },
			  '/proxy/**': { proxy: '/api/**' },
			}
		}
	}
})
```
