### ISSUE TITLE
Q : Is there a simple way to add a folder of "api" handlers nitro way

### ISSUE THREAD

**Issue by niicojs** [nksaraf/vinxi#142]
For example: 
- create an api folder
- create file `one.get.ts`, `two.post.ts`, `three.post.ts`
- expose them all in something like
```
    {
      name: 'api',
      mode: 'handler',
      middleware: './app/middleware.tsx',
      handler: './app/api/*.ts',
      target: 'server',
    },
```

**Comment by niicojs** [comment]
Looks like there is something in vinxi-router/api but there is no doc for it.

**Comment by nksaraf** [comment]
Yeah documentation is a shortcoming right now. But yes, there is a package called `@vinxi/router` that comes with some built in `router` presets. One of them is the API router.

```ts
import { createApp } from 'vinxi';
import { apiRouter } from '@vinxi/router/api';

export default createApp({
	routers: [
		apiRouter()
	]
})
```

**Comment by niicojs** [comment]
Nice thanks!
Just FYI for others if they come here:
- All Nitro sugar may not be available (like auto import)
- Nitro stuff like `.get.ts` for get only routes are not available 
- I'm guessing you mean `.ts` not `.tsx`

**Comment by nksaraf** [comment]
> Nice thanks! Just FYI for others if they come here:
> 
> * All Nitro sugar may not be available (like auto import)
> * Nitro stuff like `.get.ts` for get only routes are not available
> * I'm guessing you mean `.ts` not `.tsx`

Yup, no auto imports. Add the vite plugin from unimport if you want it. instead of the `get`/`post` in the filename, this file router allows you do that filtering in the runtime by checking the method in the event handler. Or you can implement your own file system router that follows these conventions from nitro.

**Comment by niicojs** [comment]
Thanks I'll try the unimport way. But correct me if I'm wrong but I'll have to hook it up manually cause api handlers dont go through vite are they?
