### ISSUE TITLE
Better docs for `vinxi serve`

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#164]
I'm not sure how to use the parameters with [vinxi serve](https://vinxi.vercel.app/cli#vinxi-serve). To simplify things ( [Stackblitz](https://stackblitz.com/edit/github-rhngpv?file=package.json) link ) I took the basic example, changed vinxi to v0.1.10, and tried to run vinxi serve, and it yields:

```ts
{
  "statusCode": 404,
  "statusMessage": "Cannot find any path matching /.",
  "stack": []
}
```

adding  --dir ./.output/ doesn't appear to make a difference.

sidenote - does `vinxi serve` make `vinxi start` cli command irrelevant, or is there still usecases for that?

**Comment by edivados** [comment]
serve starts a static file server. When serving `./.output/` and navigating to `/` there is no index.html and you get a 404.
Your stackblitz with `start.ssr = false` and `vinxi serve --dir .output/public`  https://stackblitz.com/edit/github-rhngpv-n2yzcw?file=vite.config.ts

> sidenote - does vinxi serve make vinxi start cli command irrelevant, or is there still usecases for that?

Two different things. start is basically the same as doing `node .output/server/index.mjs` and serve starts a statc file server that you can point to some directory and serve it's content.

**Comment by birkskyum** [comment]
Thanks, so using the preset: 'static', in combination with: `vinxi serve --dir ./.output/public/` worked
