### ISSUE TITLE
Middlewares are not preprocessed with Vite?

### ISSUE THREAD

**Issue by LexSwed** [nksaraf/vinxi#180]
I use import aliases in solid-start project, and all the server code is working correctly with [import aliases](https://vitejs.dev/config/shared-options#resolve-alias) (or [vite-tsconfig-paths](https://www.npmjs.com/package/vite-tsconfig-paths)), but middleware is failing to run with
```
[vite] Error when evaluating SSR module /src/middleware.ts: failed to import "#/server/auth/user-session"
|- Error: Cannot find module '#/server/auth/user-session' imported from solid-start-next/packages/web/src/middleware.ts'
    at nodeImport...
```

Appeared after 0.2.1 update.

**Comment by ryansolid** [comment]
This should be fixed in Start 0.5.1. This was on Solid Start's part I believe. API routes weren't pre-processing the middleware.
