### ISSUE TITLE
Nitro `crawlLinks` + Solid-Router

### ISSUE THREAD

**Issue by atilafassina** [nksaraf/vinxi#188]
At the moment Nitro is having a bad time crawling `<A>`  components because it can't [prerender](https://nitro.unjs.io/config#prerender) those routes.
This caused different kind of bugs Solid Docs SSR and we disabled.

This issue is easier to identify when setting `failOnError` to `true` together with `crawlLinks`.

**Comment by nksaraf** [comment]
Exploring this further with @atilafassina , doesnt seem to be an issue with prerender and Link tags.

Maybe something to do with it producing index.html's for all the router.
