### ISSUE TITLE
vinxi 0.3.0 - Uncaught TypeError: Cannot read properties of undefined (reading 'afterCreateSignal')

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#192]
For some reason, the new release breaks the dev mode of solid-start (0.5.5).

Trying it in the `basic` example, the counter doesn't increment in dev mode, but works in pnpm run build -> start. The error in the console reads:

```
dev.js:202 Uncaught TypeError: Cannot read properties of undefined (reading 'afterCreateSignal')
    at createSignal (dev.js:202:18)
    at $$component (@solid-refresh:96:29)
    at dev.js:1650:10
```

**Comment by nksaraf** [comment]
fixed this in [f73de3a](https://github.com/solidjs/solid-start/commit/f73de3a61f964748e456f6f714a3c290cd53379b). Will also push this fix upstream in vinxi
