### ISSUE TITLE
Website: Support link links to current page 

### ISSUE THREAD

**Issue by marvinhagemeister** [nksaraf/vinxi#196]
It should probably link to GH or some support page if it exists instead.

<img width="690" alt="Screenshot 2024-02-14 at 11 23 39" src="https://github.com/nksaraf/vinxi/assets/1062408/046f6ef3-ac0f-451f-923b-18a45e59251c">

EDIT: Looks like none of the menu entries work in that menu.

**Comment by nksaraf** [comment]
Changed the whole setup for the site.. there are still empty pages but yeah no dead links in the nav
