### ISSUE TITLE
Infinite vite.config.ts reload loop

### ISSUE THREAD

**Issue by Nvos** [nksaraf/vinxi#201]
Version 4.0 of [vanilla extract vite plugin]( https://github.com/vanilla-extract-css/vanilla-extract) when used along with [solid-start](https://github.com/solidjs/solid-start) results in infinite change detection loop on `vite.config.ts`. Seems to be happening due to temporary `timestamp` vite files.

# Log
```
vinxi 0.3.3
vinxi Found vite.config.js with app config
vinxi starting dev server
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vinxi change detected 1 in vite.config.ts.timestamp-1708343215792-222a922c5f9cd.mjs
vinxi reloading app
vinxi Found vite.config.js with app config
vinxi change detected 1 in vite.config.ts.timestamp-1708343215793-bd841f136bbf3.mjs
vinxi reloading app
vinxi Found vite.config.js with app config
vinxi change detected 1 in vite.config.ts.timestamp-1708343215796-13daa118e8c7b.mjs
vinxi reloading app
vinxi Found vite.config.js with app config
vinxi change detected 1 in vite.config.ts.timestamp-1708343218501-0dea49476940c.mjs
vinxi reloading app
vinxi Found vite.config.js with app config
vinxi change detected 1 in vite.config.ts.timestamp-1708343218502-28d8dd889ec74.mjs
vinxi reloading app
```

# Possible fix
Adding ignore on `timestamp` for vite config watcher in `packages\vinxi\bin\cli.mjs` seems to fix issue:

```typescript
watcher = chokidar.watch(
  ["app.config.*", "vite.config.*", configFile].filter(Boolean),
  {
    ignoreInitial: true,
    ignored: "**timestamp**"
  },
);
```

**Comment by nksaraf** [comment]
yeah that fix makes sense, we shouldn't listen to the temporary files vite creates with the timestamps.

Want to make a PR for this?

**Comment by Nvos** [comment]
Sure, should ignore pattern be more strict or is it fine to have it same as in snippet I provided in comment above?

**Comment by Nvos** [comment]
PR is up https://github.com/nksaraf/vinxi/pull/203

**Comment by nksaraf** [comment]
Fix is merged, and will be part of next release
