### ISSUE TITLE
DX is a lot worse with `[BABEL] Note: The code generator has deoptimised the styling of ... as it exceeds the max of 500KB.`

### ISSUE THREAD

**Issue by lominming** [nksaraf/vinxi#204]
From a thread in discord, maybe Vinxi is doing additional post-processing?

Prior to solid-start 0.4.0 (beta 2), I do not face this issue. With solid-start beta 2 (with Vinxi + Nitro), starting up in dev mode will hit these warning `[BABEL] Note: The code generator has deoptimised the styling of ... as it exceeds the max of 500KB.` 

I believe this problem largely occurs with larger packages. 

**Consequence:** It takes upwards of 2 min to load localhost:3000 when first start up. Also, running e2e tests will keep timing out because it is taking far too long.

**Question:** Is there a config somewhere that can direct Vinxi or Nitro to exclude optimizing of packages? 

**Attempts:** Tried a couple of different vite configs but nothing seems to work so far. 

Maybe @nksaraf can point to some inner workings of Vinxi to know the issue?

**Comment by nksaraf** [comment]
can i see a repro, so I can see what kind of packages we are talking about. Try the latest solid-start too and the latest vinxi (might help)

**Comment by lominming** [comment]
@nksaraf https://stackblitz.com/edit/solidjs-templates-wcv4hz?file=index.html
Load the page and see how long it takes just to render the editor, and the error messages in console.

I found part of the cause: If a large node module is loaded just on the client side (either via `clientOnly` or `import` inside `onMount`), it triggers the error. There's separate set of errors for bundling on the server. Maybe client bundling is doing unnecessary bundling for `node_modules`? 

The errors are all `[BABEL] Note: The code generator has deoptimised the styling of node_modules/.vinxi/client/deps/` <--- `client/deps`

The page loads instantly before solid-start 0.4.0 (beta 2).

**Comment by carere** [comment]
I have the same errors with lot of packaging (solidjs-icons, lightweight-chart, etc)

**Comment by lominming** [comment]
@nksaraf this problem still exists with 
```
    "@solidjs/start": "^0.6.1",
    "vinxi": "^0.3.9",
```

**Comment by birkskyum** [comment]
This is blocking me from running the dev server for an app i updated:

```sh
[BABEL] Note: The code generator has deoptimised the styling of /repo/node_modules/.vinxi/client/deps/maplibre-gl.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /repo/node_modules/.vinxi/client/deps/chunk-WWHF6SAG.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /repo/node_modules/.vinxi/client/deps/maplibre-gl.js as it exceeds the max of 500KB.
```

**Comment by nksaraf** [comment]
Yeah I could try to hide that warning, but I find it better that people see it and realize they might be using some large dependencies. 

Now, obviously this stuff might get treeshaken and eliminated during the build so the effect might not be that bad, but in dev, we (vite) don't do treeshaking

**Comment by lominming** [comment]
@nksaraf Maybe you misunderstood the problem. This is not about extraneous logs in dev mode, but that warning corresponds to **very slow start time** in dev mode. It takes 2-4 minutes after `npm run dev` to even use the page at all. Please look at the stackblitz here: https://stackblitz.com/edit/solidjs-templates-wcv4hz?file=index.html and see how long it takes for the page to be active. 

The same code on solid-start before 0.4.x (before beta-2) only takes <5 seconds to load in dev mode. Prior to 0.4.x, solid-start also uses Vite.

Somewhere somehow there's attempted optimization being made on **ALL client/deps node_modules** in dev mode. This is not a tree-shaking problem.

**Comment by nksaraf** [comment]
Surprising that earlier it was <5 seconds. i don't know what we were doing less then. maybe the babel passes for server functions or the code splitting

**Comment by nksaraf** [comment]
okay found it. its our styles crawler. Right now we crawl the whole tree. But maybe we should only crawl user code, and let people opt in to node_modules they are interested in getting CSS crawled from. You will still get the CSS needed by those node_modules lazily if you don't opt for the crawl

**Comment by lominming** [comment]
> okay found it. its our styles crawler. Right now we crawl the whole tree. But maybe we should only crawl user code, and let people opt in to node_modules they are interested in getting CSS crawled from. You will still get the CSS needed by those node_modules lazily if you don't opt for the crawl

Thank you for poking around to find the issue.

I think an opt-in makes sense because I feel like there are fewer cases where we are importing components that are expecting CSS being applied globally? 

Where is the styles crawler code? Maybe in the meantime, I can try to see whether I can temporarily patch it on our end.

**Comment by nksaraf** [comment]
@lominming checkout #258. This should give you an idea of what patch will fix this issue

**Comment by lominming** [comment]
Sorry to re-open this thread. The issue is still happening with the latest patch. I also tried to completely disable the crawler, and the messages are still happening.

I realized that they are all because of `client/deps` (e.g. `/node_modules/.vinxi/client/deps/chunk-LKZYTNS7.js as it exceeds the max of 500KB.` )

So it must be something on the client side and only in dev mode. I tried to disable a lot of the crawler functions, and none of them helped. Any other ideas?

---

**To quickly recap, anytime we include a large node package on the front end (e.g. clientOnly(() => import(...))) for packages like `monaco`, the dev experience will be heavily impacted.**

**Comment by nksaraf** [comment]
Hmm interesting so it's on the clinet.. I wonder if we even do anything extra with those.. let me see

**Comment by birkskyum** [comment]
This `[BABEL] Note: The code generator has deoptimised the styling of ` is really impacting startup time of the dev server. Would love to be disable this check.

**Comment by birkskyum** [comment]
How can I set this babel compact option?
https://babeljs.io/docs/options#compact

**Comment by birkskyum** [comment]
Alright making a babel.config.js with the following content did the trick and removed this:

```js
module.export = {
  env: {
    development: {
      compact: true
    }
  }
}
```
