### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'config') when turning on experimental.asyncContext option

### ISSUE THREAD

**Issue by FlatMapIO** [nksaraf/vinxi#235]
It works fine in development mode, but when deployed in all three cf vercel-edge nodejs targets it causes problems, and I finally managed to locate the error in the local nodejs target.

<img width="1303" alt="image" src="https://github.com/nksaraf/vinxi/assets/1720349/63bda856-1e74-48a6-abf9-86a4b9972a0c">

```tsx
!globalThis.app.config.server.experimental?.asyncContext) throw new Error("AsyncLocalStorage was not enabled. Use the `server.experimental.asyncContext: true` option in your app configuration to enable it. Or, pass the instance of HTTPEvent that you have as the first argument to the function."
```

Among other things, the `runtimeConfig`, `dev` other options in solid-start do not generate accessible properties at runtime after configuration.

**Comment by FlatMapIO** [comment]
rel #233

**Comment by nksaraf** [comment]
Can you make a github repo that reproduces this. I can try deploying it to vercel-edge

**Comment by FlatMapIO** [comment]
Sorry @nksaraf , I took the time to look into it, and there is a global scope reference to getEvent.  That was my mistake.
