### ISSUE TITLE
`event.context.params` is empty when using `apiRouter`

### ISSUE THREAD

**Issue by alessandrojcm** [nksaraf/vinxi#242]
Hi tehre, I am playing around with the `apiRouter` from `@vinxi/router`. I've noticed that the `event.context.params` from the event passed to the API route handlers is empty, hence making functions like `getRouterParam` fail. I know that the params are passed as a second argument to `defineEventHandler` but I believe it would be good to pass them as pass of the `event` object to make it more inline with H3 (also making H3 code directly portable, which is my case).

Reading the [API Handler](https://github.com/nksaraf/vinxi/blob/main/packages/vinxi-router/api-handler.js#L35) code, I believe just adding the `params` object to `event.context` would be sufficient, I may be missing something but if I am not I would be happy to make that PR.

**Comment by nksaraf** [comment]
I think you're right, we should just do that. Would love to merge that PR once its done
