### ISSUE TITLE
Route rules cache.maxAge not working with public assets

### ISSUE THREAD

**Issue by edivados** [nksaraf/vinxi#245]
Because `publicAssets` entries are all set to `fallthrough: true` the cache.maxAge option will not work and you have to use headers instead to define cache-control.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/solidjs-solid-start-vdadwq?file=app.config.ts)

Nitro will only apply cache.maxAge if fallthrough is false.
https://github.com/unjs/nitro/blob/b0f08c1c3b1b9e530c0ff9731aba399fd8ada0c3/src/nitro.ts#L85-L95

This makes me question if a better default would be to not set `fallthrough` and expose this option on the router for more specific use cases.

> [!NOTE]  
> For nitro `/` is fallthrough by default if not defined. This is not a real config just an example for the option on the router.

``` js
[
 {
    name: "public",
    type: "static",
    fallthrough: true
  },
  {
    name: "client",
    type: "client",
    assets: {
      fallthrough: true
    }
  }
]
```

**Comment by nksaraf** [comment]
Honestly, I think people should just headers to drive this stuff anyway: 

```ts
headers: {
    "cache-control": `public, max-age=${asset.maxAge}, immutable`,
  }
```

The highler level API is adding almost nothing and magically doesn't work for these inside edge cases. 

I don't want to add new APIs if not needed, and someone setting `fallthrough: false` will probably break everything (i think)

**Comment by edivados** [comment]
> The highler level API is adding almost nothing and magically doesn't work for these inside edge cases.

Fair it doesn't add much. Not sure what edge cases you are referring to but in those cases `cache-control` wouldn't work either because cache.maxAge tells Nitro to add the `cache-control` header to the route rule.

> I don't want to add new APIs if not needed, and someone setting fallthrough: false will probably break everything (i think)

Understandable and independent of `cache.maxAge` `fallthrough` can be changed with a hook if necessary. I guess this means `cache.maxAge` is not supported and the recommended way is to use `headers` in Vinxi. 

I am ok with that and will close this.

<hr>

 If `fallthrough` should not be set by default could be separate topic. I am not sure when you would want requests for assets to fallthrough by default. Need to work with it more to see what a better default is. Right now I tend towards false.
