### ISSUE TITLE
Local HTTPS development with vinxi.

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#257]
Usually, I'd configure HTTPS inside the vite.server.https, vite.server.host, vite.server.port, and vite.plugins (vite-plugin-mkcert / vite-plugin-basic-ssl)

It seems like `vinxi dev` is ignoring anything from the vite.server.

**Comment by nksaraf** [comment]
yup there's no vite server really, its used as a transform pipeline, the server is nitro/h3. For https during dev.. you can set `server.https: true` (and it probably has other options to configure https

**Comment by birkskyum** [comment]
Thanks, it does indeed load on HTTPS. The TS didn't recognize the flag, and i need some cert config etc., but good progress

<img width="431" alt="Screenshot 2024-03-16 at 14 46 40" src="https://github.com/nksaraf/vinxi/assets/74932975/753fd357-4732-4454-9d21-eb371c7155ee">
<img width="419" alt="Screenshot 2024-03-16 at 14 46 46" src="https://github.com/nksaraf/vinxi/assets/74932975/b53c0265-fc4e-4763-af9f-fc861ad92ac0">

**Comment by timothyallan** [comment]
> Thanks, it does indeed load on HTTPS. The TS didn't recognize the flag, and i need some cert config etc., but good progress

Did you ever figure out how to load a cert/key ?

**Comment by birkskyum** [comment]
@timothyallan , no, i found that https without locally signed certs worked for my use case. There are some env vars that are mentioned here which is probably the way to do it: https://github.com/unjs/nitro/issues/749#issue-1491576157

**Comment by timothyallan** [comment]
he, I'd just figured it out a few minutes after I posted my now deleted post :)

after a random guess, I tried :
```
server: {
    https: {
      key: ".cert/mykey.pem",
      cert: ".cert/mycert.pem",
    },
```
and it worked.

**Comment by birkskyum** [comment]
So we need types for this in config
