### ISSUE TITLE
Unable to change hmr port - `WebSocket server error: Port is already in use`

### ISSUE THREAD

**Issue by ap32** [nksaraf/vinxi#260]
I'm not entirely sure, but I think this is a vinxy bug. I'm using @solid/start and when I try to change `hmr.port` I get an error. The server starts, but hmr does not work
```
vinxi v0.3.10
vinxi starting dev server
WebSocket server error: Port is already in use
WebSocket server error: Port is already in use (x2)
```

**Comment by nksaraf** [comment]
We internally use random ports for hmr port. Thats because we have different HMR servers for internal parts, so multiple ports are being used. 

If you have a very strong reason to use a specific HMR port, would love to know it and support the use case.

**Comment by NathanSMB** [comment]
The use case I ran into was for devcontainers. You need to be able to expose the port(s) in docker in order for HMR to work.

**Comment by ap32** [comment]
I am using `@solid/start` inside docker container.
Was able to solve this problem by checking if `router === "client".
```
export default defineConfig({
  vite({ router }) {
    return {
      server: {
        port: 3000,
        strictPort: true,
        hmr:
          router === "client"
            ? {
                protocol: "wss",
                port: 22300,
                clientPort: 443,
                path: "hmr/",
              }
            : {},
      },
    };
  },
});
```

**Comment by N0tExisting** [comment]
For me this is quite anoying, because I am using VSCode-Remote-SSH, and that only forwards ports if an URL gets printed in the CLI.
VSCode also never stops forwarding the port unless you stop it manually, which is why the usage of random ports is anoying.
