### ISSUE TITLE
vite 5 support

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#28]
to allow downstream projects to use vite 5, as discussed here:
https://github.com/solidjs/solid-start/pull/1139#issuecomment-1861620400

i tried bumping it in the packages/vinxi, and then a handful of the tests broke, so there might be some adjustment needed.

```sh
  5 failed
    [chromium] › basic-prod.test.ts:35:2 › basic build › ssr 
    [chromium] › fs-router.test.ts:36:2 › fs-router › ssr 
    [chromium] › hmr.test.ts:87:2 › hmr › client hmr 
    [chromium] › rsc.test.ts:36:2 › rsc › spa 
    [chromium] › srv-fn.test.ts:68:2 › srv-fn-prod › spa 

  3 skipped
  6 passed (10.8s)
```

**Comment by nksaraf** [comment]
I added support for Vite 5 with 68cab94f1ae5731b6e550d1d6296bdb9ece21ed1

You can use pnpm/yarn/npm overrides or resolutions to force vite to version 5 and try it out. Eventually we will shift to vite 5 as the default once other parts are more stable.
