### ISSUE TITLE
Missing types for server.https

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#280]
https can be either bool or

https: {
      key: ".cert/mykey.pem",
      cert: ".cert/mycert.pem",
    },

Related
- https://github.com/nksaraf/vinxi/issues/257

**Comment by edivados** [comment]
Oh... ok. I may have forgotten to add the type to the config or it was different at the time.

The type [should be](https://github.com/nksaraf/vinxi/blob/4bddafe1b7e873ef691392ebaf7ea4f4875e39d4/packages/vinxi/lib/dev-server.js#L10).
```
https?: import('@vinxi/listhen').HTTPSOptions | boolean
```

The final `{ key, cert }` is generated with an originaly internal helper exported in `@vinxi/listhen`. This is then passed to vite and listhen.

https://github.com/nksaraf/vinxi/blob/4bddafe1b7e873ef691392ebaf7ea4f4875e39d4/packages/vinxi/lib/dev-server.js#L117-L119
