### ISSUE TITLE
vinxi dev unable to start dev server

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#287]
I'm not sure what causes this, but I can wait minutes on the vinxi dev to start up, and sometimes it never succeeds. I have to restart the process after a few minutes until it eventually completes

**Comment by nksaraf** [comment]
Is there a reproduction for this ?

**Comment by birkskyum** [comment]
I can't reproduce it consistently. Most times it's up fast enough, but sometimes it just hangs. I'll make a ticket if I can reliably repro.

**Comment by birkskyum** [comment]
I might just have had connectivity issues actually.

**Comment by birkskyum** [comment]
just to give an idea of what i experience, it's this infinite load that eventually stops (can be stuck for >10min), and then suddenly after one of many restarts load the page immediately

https://github.com/nksaraf/vinxi/assets/74932975/cee0f873-0c56-4d09-9446-31024cf680aa

**Comment by birkskyum** [comment]
it got stuck when I changed in this file.. those filenames looks weird.


<img width="437" alt="Screenshot 2024-04-29 at 22 24 20" src="https://github.com/nksaraf/vinxi/assets/74932975/72407e22-829d-4858-9b86-b0b3adc6bd22">

**Comment by birkskyum** [comment]
seems like some infinite loop with this:
- https://github.com/vitejs/vite/issues/5675

**Comment by birkskyum** [comment]
<img width="841" alt="Screenshot 2024-05-17 at 15 06 28" src="https://github.com/nksaraf/vinxi/assets/74932975/b8d2ef58-b75d-4d9d-9df8-4a2e1c7276d3">

**Comment by birkskyum** [comment]
This appear to be limited to `ssr: true`

**Comment by birkskyum** [comment]
And when hitting a routes/page/[id]/ page after a server restart

**Comment by birkskyum** [comment]
I'm getting closer. It's related to signal created outside of the root node.

**Comment by birkskyum** [comment]
So at this point, I'm just disabling ssr when developing, and enabling it when deploying.

**Comment by birkskyum** [comment]
@doeixd , do you see this too? are you able to repro?

**Comment by birkskyum** [comment]
Had less issues with this after switching to bun.

**Comment by birkskyum** [comment]
Don't know if fixed by vinxi 0.4.1 - will close for now.
