### ISSUE TITLE
Feature request: CLI shortcuts in dev

### ISSUE THREAD

**Issue by shiro** [nksaraf/vinxi#29]
Hello,
I know it's not high priority, I just wanted to suggest bringing back the CLI keyboard shortcuts solid start had.

I.e. `press 'r' to restart server`.

Thank you for the good work :bow:

**Comment by nksaraf** [comment]
Would you be interested in contributing this feature. Should be similar to how it was implemented in solid-start earlier.

**Comment by shiro** [comment]
Not right now, but if I have enough time I might look into it at some point.

If someone wants to take it, feel free to do so :+1:
