### ISSUE TITLE
The function findAssetsInViteManifest can slow down SSR significantly

### ISSUE THREAD

**Issue by jean343** [nksaraf/vinxi#332]
In production mode, the function `findAssetsInViteManifest` is called multiple times in SSR mode.

With a large app and many dependencies, it can take a long time to execute. SSR time goes up from 9ms to 900ms.

<img width="813" alt="image" src="https://github.com/user-attachments/assets/2cf84416-7f83-4f8e-8a10-149afb268b66">

Problem is that the assetMap cache contains duplicate entries, multiple thousands in our case.
One solution would be to remove duplicates before storing them in the map.
```js
const all = Array.from(new Set([...assets, ...imports])).filter(Boolean);
return all;
```

Before the change:
![image](https://github.com/user-attachments/assets/e7dca4c0-b32a-477c-a108-49e7734aa19e)

After the change:
![image](https://github.com/user-attachments/assets/3cac200f-f24e-438a-9c60-e63742f99658)

**Comment by lominming** [comment]
Thank you for posting this. We have been fighting with performance issue for a while, and have spent the past 3-4 weeks drilling down to all parts of the code Solid-Start and Vinxi code. 

@jean343 Did you short-circuit the rest of the function by immediately `return all` (Version B)? Or did you only replace the `filter` line (Version A)? When we did our test, Version A (one line change) saw a 10x improvement. We did not see any performance change with (Version A vs B).

```js
// original code
const all = [...assets, ...imports].filter(Boolean);
all.push(chunk.file);
assetMap.set(id, all);
stack.pop();
return Array.from(new Set(all));
```

```js
// Version A
const all = Array.from(new Set([...assets, ...imports])).filter(Boolean); // <--- line change
all.push(chunk.file);
assetMap.set(id, all);
stack.pop();
return Array.from(new Set(all));
```

```js
// Version B
const all = Array.from(new Set([...assets, ...imports])).filter(Boolean); 
return all; // return early
// all.push(chunk.file);
// assetMap.set(id, all);
// stack.pop();
// return Array.from(new Set(all));
```

**Comment by katywings** [comment]
I'd love to make a PR fixing this. Thank you both for all the information and the potential solution! Can you please give me a reproduction regarding the duplicate entries, best would be a zip, but it can also be a quick step by step list. I just wanna be able to test the PR with a project that actually has the problem 😅.

**Comment by jean343** [comment]
It's version A above, I have a full diff for you if it helps.

```diff
--- a/node_modules/vinxi/lib/manifest/vite-manifest.js
+++ b/node_modules/vinxi/lib/manifest/vite-manifest.js
@@ -29,20 +29,23 @@ const findAssetsInViteManifest = (manifest, id, assetMap = new Map()) => {
 		}
 
 		stack.push(id);
-
+		const dynamicImports = id.startsWith('virtual:') ? undefined: chunk.dynamicImports;
 		const assets = [
 			...(chunk.assets || []),
 			...(chunk.css || []),
 			...(chunk.imports?.flatMap(traverse) || []),
+			...(dynamicImports?.flatMap(traverse).filter(i => i.endsWith(".css")) || []),
 		];
 		const imports = chunk.imports?.flatMap(traverse) || [];
-		const all = [...assets, ...imports].filter(Boolean);
+		const all = Array.from(new Set([...assets, ...imports])).filter(Boolean);
 		all.push(chunk.file);
 		assetMap.set(id, all);
 
 		stack.pop();
 
-		return Array.from(new Set(all));
+		return all;
 	}
 	return traverse(id);
 };
```

It's difficult to make a reproduction, the previous algorithm is O(n2), and it gets noticeably slow after about 4000 imports. You could make a unit test with a large manifest input!

**Comment by ryansolid** [comment]
I wonder if this why people have been saying code splitting in routing is slow. It should be an easy perf win but if it enlarges the size of these asset manifests then that could definite do it.

**Comment by ryansolid** [comment]
There is some odd stuff in this function without even looking deeper in the code.. for example it traverses imports and spreads them in twice seemingly unnecessarily? Also I'm not sure that the Boolean Filter is necessary.In anycase because it's recursive we shouldn't have to filter at ever layer just on the leaves.  And part of me wonders would we gain performance by deduping at the end instead of at each step. 

I really wish I had a reproduction or just an example of what a large manifest looked like. I can definitely make this faster, but I think the slowdown depends on shape. But with the manifests I'm dealing with at best I've made it 2x faster as they aren't that big. It's possible the performance character could completely change in your use cases depending on shape of manifest.

So I'm not sure how to proceed. I can release something and see if it helps... but I'd rather be able to test something real. I don't need your code just console.log the manifest.

**Comment by jean343** [comment]
I am trying right now, the initial code takes 3.8 seconds.
Your version 1 takes 15ms
Your version 2 takes 46ms
Those timings are the entire SSR time and include more than this function time.

Note that it calls the function 46 times for a single page load, some times it's longer and some other times it's fast.

```
findAssetsInViteManifest: 0.106ms
findAssetsInViteManifest: 0.623ms
findAssetsInViteManifest: 0.489ms
findAssetsInViteManifest: 1.737ms
findAssetsInViteManifest: 0.339ms
findAssetsInViteManifest: 0.582ms
findAssetsInViteManifest: 0.143ms
findAssetsInViteManifest: 0.087ms
findAssetsInViteManifest: 0.009ms
findAssetsInViteManifest: 2.757ms
findAssetsInViteManifest: 10.715ms
findAssetsInViteManifest: 7.737ms
findAssetsInViteManifest: 5.393ms
findAssetsInViteManifest: 0.021ms
findAssetsInViteManifest: 34.103ms
findAssetsInViteManifest: 85.149ms
findAssetsInViteManifest: 606.861ms
findAssetsInViteManifest: 0.059ms
findAssetsInViteManifest: 80.593ms
findAssetsInViteManifest: 0.017ms
findAssetsInViteManifest: 1.848ms
findAssetsInViteManifest: 0.006ms
findAssetsInViteManifest: 1.943ms
findAssetsInViteManifest: 72.98ms
findAssetsInViteManifest: 0.018ms
findAssetsInViteManifest: 0.002ms
findAssetsInViteManifest: 0.004ms
findAssetsInViteManifest: 28.506ms
findAssetsInViteManifest: 0.133ms
findAssetsInViteManifest: 0.133ms
findAssetsInViteManifest: 0.039ms
findAssetsInViteManifest: 0.205ms
findAssetsInViteManifest: 0.323ms
findAssetsInViteManifest: 0.037ms
```

I will send you the manifest, I would prefer not pasting it in a public channel.

**Comment by ryansolid** [comment]
Yeah it's because every dynamic import needs to grab it separately which why there is so much variance. This does confirm though I think that deduping at each level is beneficial for your type of graph. I was worried there wouldn't be much of a difference. It's ok about the manifest if you don't want to. I'm ok going with the first option here after seeing that.

**Comment by jean343** [comment]
I'm glad it helped, the speedup is massive for our use case.
I have sent you the manifest through a private channel.

**Comment by lominming** [comment]
@ryansolid Adding some addition data points from my end. My app is fairly complex.

All the numbers below are for an essentially blank page on our app. Numbers are from local machine production build + start. This page has 28 requests. 

## Additional info
When debugging this, we logged how many times `findAssetsInViteManifest` was called, and also store the cumulative length/size of `[...assets, ...imports]` for the simple blank page:

- `findAssetsInViteManifest` was called `2,154 times` for a single page load (some other pages ended up with 16k calls)
- Total combined length of `[...assets, ...imports]` was `224,173`, which was filtered down to `40,449`
- For each run of `findAssetsInViteManifest` the size of `[...assets, ...imports]` varies, the largest I've seen is around `3,xxx`.

## Baseline (without any change)
- First load: ~850ms 
- Finish: ~1.1s

## With a one line change
Replace `const all = [...assets, ...imports].filter(Boolean);` with `const all = Array.from(new Set([...assets, ...imports])).filter(Boolean);`
- First load: ~35ms
- Finish: ~360ms

## Your V1
- First load: ~23ms
- Finish: ~300ms

## Your V2
- First load: ~70ms
- Finish: ~340ms

These are just our "empty page". Happy to test our more complex pages. Huge performance gains on my end too.

**Comment by ryansolid** [comment]
The only thing giving me pause is that it appears micro-optimizations in this routine are still impacting overall time which means it is still a bottleneck and we can probably do better. I probably should just ship this first though because it is such a significant improvement.

**Comment by ryansolid** [comment]
Ok.. I have released the next version. I was able to unwind the flatMap and remove closures make it another 33% faster but I'm at my limits of micro-optimizations. The real question is if the assetMap can be shared across more calls. Or if SolidStart can make less calls. Still a huge win here I think.
