### ISSUE TITLE
Consider adding a README.md to the main `vinxi` package

### ISSUE THREAD

**Issue by scotttrinh** [nksaraf/vinxi#338]
I was reviewing a PR from a community member adding some SolidStart functionality and noticed that they imported `vinxi`, so I searched on npm to see what this package was about and saw a totally blank package entry. After hunting around for another 5 minutes or so, I came across reference to vinxi in the Solid docs and then found the repo through Google. Given the high profile issues with supply-chain security in JS land, it would be a good signal to others if the package published a README and a link to this repository in the package.json for the main package.

Happy to jump in and help if you have an idea about how you want to handle the README situation.

**Comment by nksaraf** [comment]
PRs are very welcome and solicited!
