### ISSUE TITLE
startup / dispose hooks?

### ISSUE THREAD

**Issue by Torsten85** [nksaraf/vinxi#34]
Hello,
I like to initialize a db connection on startup and also close this connection when the dev server reloads. Is there a way to hook into this? Thought of `import.meta.hot`, but that does not work. Also I couldn't find a Signal to listen to like `process.on('SIGTERM'...`

thanks in advance

**Comment by nksaraf** [comment]
Okay so we need hooks for startup, dev-server-reload, SIGTERM. Let me see how I can provide these. What do you mean by startup exactly?

**Comment by Torsten85** [comment]
@nksaraf  thanks for your quick answer!

I think a startup hook is not necessarry (at least for me) when it's not considered "bad practice" to simply execute code in the global scope of a file (e.g. establish a database connection).

My specific use case at the moment is a device that is connected to the server via a serial port. Before the dev server reloads, I have to disconnect the port so it's not busy when the script gets executed again.

I'm trying out the new solid start beta 2, but I think this is the repo where such functionality has to be implemented, right?

**Comment by nksaraf** [comment]
Yup yup! Okay so a hook into when the dev server reloads, sure ill come up with something

**Comment by Torsten85** [comment]
Great! Looking forward to what you come up with 😉 Thanks!

**Comment by katywings** [comment]
> I think a startup hook is not necessarry (at least for me)

Imho the startup/dispose hooks would be very useful, especially to handle long running processes like websockets 😅. And Reload could be an own hook, or even a chained dispose->startup call 🤔

**Comment by nksaraf** [comment]
I have added some hooks to the dev server in `vinxi:0.0.57`. So you can hook into things by calling `app.hooks.hook("...", () => {... })`.

You can checkout the order of hooks here. Each hooks also comes with some data like an instance of the app, along with the dev server, etc.

<img width="530" alt="Screenshot 2023-12-29 at 12 56 56 AM" src="https://github.com/nksaraf/vinxi/assets/11255148/7632d8ee-ca8c-4cd3-9ac9-aafabf7217c4">

Inside your application you can access the app via globalThis.app. I might create a helper function for this but ideally don't want this exposed too much yet until we know what might people do with it.

**Comment by Torsten85** [comment]
thanks @nksaraf , this looks promising... but I'm actually not sure how to use those hooks.

Maybe you could have a look at this demo repo: https://github.com/Torsten85/vinxi-hooks

Im trying to make a connection on startup (ideally before using a server function) and closing the connection on dev server reload. None of the hooks get called when I e.g. change a line in my `./app/db.ts` file.
