### ISSUE TITLE
Add license field to packages

### ISSUE THREAD

**Issue by thomasballinger** [nksaraf/vinxi#343]
Would you be open to adding `"license": "MIT"` to the package.json of all packages? This is selfish, I use a home-grown license scanner that looks for this field and I have add exceptions for vinxi packages since from [LICENSE](https://github.com/nksaraf/vinxi/blob/main/LICENSE) and the LICENSE found in each of the [published packages](https://unpkg.com/browse/@vinxi/server-functions@0.4.1/) I can tell that these are licensed MIT.

**Comment by nksaraf** [comment]
yup go ahead, make a PR!
