### ISSUE TITLE
`vinxi dev` doesn't load .env properly with Deno

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#346]
With `vinxi dev` the .env is with Node loaded automatically, but when using Deno the env vars doesn't appear to be picked up. Latest version of Deno (deno upgrade --canary) use the --env-file just like Node and Bun. 

Prior versions of Deno used --env, which now just forwards to --env-file.

**Comment by fro-profesional** [comment]
Do you have and example of vinxi running with deno?

**Comment by birkskyum** [comment]
I believe it's resolved in Deno 2

**Comment by Ciantic** [comment]
I'd still like to have an example, to me vinxi gives errors such as 500 internal server error when trying to serve files.

**Comment by birkskyum** [comment]
@Ciantic , I'm able to run virtually all the solid start examples with deno as is:

deno run -A npm:create-solid
Select: SolidStart, TypeScript, pick an example example
deno i
deno task dev

Does that suffice?

**Comment by Ciantic** [comment]
Damn, I've been trying for days, it just doesn't work. I've opened bug reports everywhere :D I will try more

**Comment by birkskyum** [comment]
@Ciantic , make sure to run latest deno `deno upgrade` with 2.0.3 i believe they're at now

**Comment by Ciantic** [comment]
@birkskyum okay, my problems begins when I try to "use server", and import e.g. `jsr:@db/sqlite` I have my test repo here: https://github.com/Ciantic/deno-solid-test/

That solid starter is using node compatibility mode where you cannot do `jsr:` imports

**Comment by birkskyum** [comment]
I've tried it out, and I agree, it'll break if you lean both left (node-compat) and right (embrace deno). Made a ticket:
- https://github.com/denoland/deno/issues/26569
