### ISSUE TITLE
No way to share singleton between Nitro plugin and routers

### ISSUE THREAD

**Issue by toakleaf** [nksaraf/vinxi#387]
As discussed in a [previous issue](https://github.com/nksaraf/vinxi/issues/131), Nitro's storage layer is for some reason not available within vinxi. [It was suggested](https://github.com/nksaraf/vinxi/issues/131#issuecomment-1913732473) to simply use the unstorage library directly.  The issue with this approach is that unstorage needs to be instantiated in a singleton somewhere, most typically in a Nitro plugin that runs after server start up.  If I want to be able to populate data in that singleton then I need to have the file under reference be consistent between the Nitro plugin file and the router entrypoint file.  However, on build, for some reason these two diverge.

[Here is a stackblitz example](https://stackblitz.com/edit/github-h29qjn?file=app%2Fserver.tsx). Note how after building ` npm install && npm run build && npm start` the `keyValueStore` added to the singleton in `nitro-plugins/test.ts` is not available in the `server.tsx`.

Please let me know if there is some special configuration I can do to externalize this singleton so that the build doesn't double reference the file in the `runtime.mjs` output. I've tried many things and the only one that works consistently is to put the singleton in a completely separate npm package. However, it would be nice if this just worked out of the box as it does when using Nitro directly.

Finally, as I think you're already aware, plugins simply don't work at all in dev mode (which is actually acceptible for my use case).

**Comment by toakleaf** [comment]
Update: The hack solution of putting the singleton in a separate package only actually works when using pnpm or yarn. Issue persists with npm

**Comment by toakleaf** [comment]
Update: Found resolution. Closing issue.

If anyone else has this issue, the solution is to configure the `rollupConfig` of the `server` to mark any files you don't want to be bundled when running `vinxi build` as `external`. In addition I also found it necessary to configure a `server.alias` to these files to get the externalization to work properly. They obviously must also be javascript.

example:
```javascript
export default createApp({
  server: {
    alias: {
      '@external': path.resolve(path.resolve(), '@external'),
    },
    plugins: ['./nitro-plugins/whateverPlugin.ts'],
    rollupConfig: {
      external: [
        path.resolve(path.resolve(), '@external', 'keyValueStore.js'),
      ],
    },
  },
});
```

and then in `whateverPlugin.ts`

```typescript
import { keyValueSingleton } from '@external/keyValueStore.js';
```

**Comment by toakleaf** [comment]
### Edit: Update

This still isn't great. The above solution I described does in fact externalize the import but it does so via hardcoding an absolute path into the built output. You can then write a custom rollup plugin to find and replace these, while also copying over the source files to built output, but it feels like no more of a solution than simply putting all your code into a separate file linked package.

I'm going to reopen this issue because I think there can be a much better flow for the incredibly common need for sharing in-memory data between Nitro plugins and routers. Without Nitro's built in implementation of `unstorage`, singletons are kind of a must, and they're incredibly harrowing to implement right now.

**Comment by katywings** [comment]
@toakleaf I know, suboptimal workaround, but have you thought on just storing your singleton in [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis)? Thats how I am solving my singleton needs at the moment 😅

**Comment by katywings** [comment]
Related issue: #51

**Comment by toakleaf** [comment]
Thanks @katywings. I had totally forgot about globalThis as an option. I guess I'll go with that solution and close down the issue again. Still feels a little bit like a hack, but there are probably more pressing issues that can get the oxygen
