### ISSUE TITLE
Vinxi does not free up port immediately when process is exited

### ISSUE THREAD

**Issue by phong-phuong** [nksaraf/vinxi#396]
Hi,

I've noticed Vinxi (verrsion 0.4.3 and lower) does not immediately free up the last used port upon exit, and will continue to run until some period afterwards, then it closes.

It would be ideal if the port and processes be closed upon exit or forced exit (ctrl+c) for example, to avoid users having to use the next available port.

**Comment by nksaraf** [comment]
Hmm never noticed this is there a repro? Also do you have any suggestions as to why this would happen.. not doing anything on my side to hold the port for any longer that my process needs to exist

**Comment by phong-phuong** [comment]
Thanks for the info. It is related to bun, as bun is still running as a background process (at least on Windows) even after ctrl+c.
