### ISSUE TITLE
Update to nitro 2.10

### ISSUE THREAD

**Issue by thdxr** [nksaraf/vinxi#409]
the latest version of nitro has a bunch of fixes and better support for streaming on aws - would like vinxi to update so tanstack/solid-start can take advantage of these features

**Comment by agoldstein03** [comment]
I've had a more recent version of nitro installed along side of vinxi and @solidjs/start, and that's been working well so far, I seem to have access to all the fixes. No clue if I'm missing some issues there, might not be best practice. For context, I'm using pnpm and had to install nitro to access some plugin helpers

**Comment by ryansolid** [comment]
Yeah definitely. Nitro 2 brings a lot of fixes especially to the adapters. I will see if I can get this prioritized.

**Comment by nksaraf** [comment]
Done in #422
