### ISSUE TITLE
Expand CI test matrix from Node 18 to 18/20/22

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#413]
The CI currently only check Node 18:

https://github.com/nksaraf/vinxi/blob/b0ccb64d3c37488050eb9411be4290ea466c3eba/.github/workflows/test.yml#L30

The active and current LTS version of Node is [Node 20/22](https://endoflife.date/nodejs).

I'm sure a lot of people, myself included, use these versions.

**Comment by codebryo** [comment]
I fully agree. 
Would even argue it would make sense for a project like Vinxi to drop official 18 support.

While Vite states 18 and 20+ are supported, the v18 support is getting less in the eco system.

Nitro officially only states latest LTS, so I guess that while 22 is the latest LTS, 20 will be supported for a longer period as well.

**Comment by birkskyum** [comment]
@codebryo , I was thinking maybe dropping node 18 in 5 months, when it's security support expires. Does that sounds reasonable to you?

https://endoflife.date/nodejs
