### ISSUE TITLE
[Issue] Dev mode is working and Build + Start mode not working

### ISSUE THREAD

**Issue by qlaffont** [nksaraf/vinxi#45]
Hi,
I'm using vinxi with solid start template and currently when I develop in dev mode, i have no issue and all my plugins are loaded successfully.

But in build mode, my plugins are not loaded : 
```bash
solid-devtools/vite
vite-multiple-assets
@vitejs/plugin-legacy
```

And my compiled version return an error : 
```bash
e is not a function
```

How is it possible to debug the output ? 

Regards

**Comment by nksaraf** [comment]
Could you provide a repro? Are you using a solid-start example from that repo? Could you specify which one?

A nice github repository with the repo would be helpful in solving these issues

**Comment by qlaffont** [comment]
Version with plugin not loaded : https://github.com/qlaffont/test-cmp

**Comment by nksaraf** [comment]
When I am building this building and running it, I am not getting any errors. Can you try this with the latest versions of everything. and a screenshot of the situation under which the error happens.

**Comment by nksaraf** [comment]
Reopen this issue if this persists with the latest release (0.0.55)

**Comment by qlaffont** [comment]
@nksaraf error is still present.

The repo I have sent, was about plugins who are not loaded.
I have push on the last commit of this repo the issue with `e is not a function` is due to vidstack component it seems
