### ISSUE TITLE
"Should be provided by compiler" Error

### ISSUE THREAD

**Issue by Numnumberry** [nksaraf/vinxi#77]
Initializing a basic SolidStart project, then running **build** and **start** will result in
![image](https://github.com/nksaraf/vinxi/assets/22666749/bbd8ffc5-8bed-4a99-8daf-7b83d13fdbcc)

This also occurs with vinxi version 0.0.62

**Comment by brenelz** [comment]
Guessing this is using `npm` instead of `pnpm`?

**Comment by Numnumberry** [comment]
> Guessing this is using `npm` instead of `pnpm`?

Yes! should I be using pnpm?

**Comment by brenelz** [comment]
I know there was a similar issue with npm previously but i thought it was fixed. pnpm seems to work i think

**Comment by Numnumberry** [comment]
> I know there was a similar issue with npm previously but i thought it was fixed. pnpm seems to work i think.
> 
> Ideally it would work with npm as well

Yes it looks like pnpm works.
I believe I have other npm related bugs to report, so I wanted to make sure it was not expected to only use pnpm.

**Comment by edivados** [comment]
For whatever reason npm installs two vinxi versions. Maybe because solid-start doesn't declare vinxi as peer dep?

1. The one in your projects package.json (whatever that is)
    - /node_modules/vinxi
2. The one solid-start declares in devDependencies (0.0.54 - assuming you are using the latest release)
    - /node_modules/@solidjs/start/node_modules/vinxi

Number 2 is what is being used during build and leads to no routes config being generated.

One thing you could do is change vinxi to `0.0.54` in your package.json or use overrides to force a specific vinxi version.

**Comment by Numnumberry** [comment]
> For whatever reason npm installs two vinxi versions. Maybe because solid-start doesn't declare vinxi as peer dep?
> 
> 1. The one in your projects package.json (whatever that is)
>    
>    * /node_modules/vinxi
> 2. The one solid-start declares in devDependencies (0.0.54 - assuming you are using the latest release)
>    
>    * /node_modules/@solidjs/start/node_modules/vinxi
> 
> Number 2 is what is being used during build and leads to no routes config being generated.
> 
> One thing you could do is change vinxi to `0.0.54` in your package.json or use overrides to force a specific vinxi version.

This does look to be the case. There is a mismatch in versions between those two locations and the behavior stays the same no matter which version I npm install (meaning it only uses the one solid-start declares).

I wanted to use greater than 0.0.54 because better CSS Modules support was added. I am not sure about overrides, but pnpm seems to be working great at the moment.

**Comment by LexSwed** [comment]
[overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) should work for now, otherwise we need to wait for Ryan to cut a new release of `@solidjs/start` with `vinxi` updates.

**Comment by nksaraf** [comment]
yup a new solid-start release is needed for this
