### ISSUE TITLE
dev-server on https

### ISSUE THREAD

**Issue by indeyets** [nksaraf/vinxi#81]
I'm porting solid-start application from 0.3 to 0.4. Previously, I could specify this in vite.config and dev-server started to work over https, which is really useful for my scenarios.

```js
{
  server: {
    https: {
      cert: 'file.pem',
      key: 'file-key.pem'
    }
  }
}
```

I don't need this for production, which uses reverse-proxies in my case. But for dev-server this is very important.

**Comment by indeyets** [comment]
@edivados did some implementation here. I didn't have chance to test it, but looks good https://github.com/nksaraf/vinxi/compare/main...edivados:vinxi:dev-https

**Comment by edivados** [comment]
Thanks for the reminder. I just need to test the last changes.
