### ISSUE TITLE
show vite version with "vinxi dev"

### ISSUE THREAD

**Issue by birkskyum** [nksaraf/vinxi#92]
Using "vinxi build" shows the vite version like this:

<img width="377" alt="Screenshot 2024-01-05 at 02 24 33" src="https://github.com/nksaraf/vinxi/assets/74932975/ba7f7fef-00a2-4624-841e-c35200e7287b">

It's quite convenient to check which version is active. "vinxi dev" on the other hand doesn't:

<img width="294" alt="Screenshot 2024-01-05 at 02 25 29" src="https://github.com/nksaraf/vinxi/assets/74932975/6ae7fa88-9bf3-4fb3-98dd-a23e01fcadcf">

**Comment by nksaraf** [comment]
Makes sense. Should we also show nitro/h3/rollup versions? they are all integral to the system. But yeah vite is probably a big piece for the dev. 

Would you like to make a PR for this?

**Comment by birkskyum** [comment]
Sure, but I don't see how I can get the vite version. I can't just look it up in the package.json, because it could be overwritten by "resolutions", so I effectively have to execute "vite -v" to get the active version, which I'm unsure how to do, and print that output.

**Comment by nksaraf** [comment]
That will also not work coz vite is not installed explicitly in Vinxi apps. It's an internal dependency. 

There is a place where I get the version and do some conditional logic for vite 4 vs 5. You can find the hint there .
