### ISSUE TITLE
[Bug?] Config changes not applied on server restart

### ISSUE THREAD

**Issue by edivados** [nksaraf/vinxi#94]
After changes the import in `loadFile` will return the config it loaded on the first start.  I am using a timestamp query param as workaround for now. 

Any better way to solve this? I have seen that there is the possibility to import modules with data urls but couldn't get that to work.

**Comment by nksaraf** [comment]
I think timestamps are perfect for this kind of stuff. How are you using them right now? Yeah I realized the dev server issue a tad bit too late

**Comment by edivados** [comment]
> How are you using them right now?

Not sure I understand what you are asking. How I use the timestamp?

**Comment by nksaraf** [comment]
Ohh query params! And the resolution works ? That's great. Let's just implement it by default in our dev server
